### ISSUE TITLE
Env vars as a map

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-cloud-run#197]
Support providing env vars as `map(string)` of k/v rather than list of objects. @prabhu34 any concerns with this for a future breaking change?

**Comment by prabhu34** [comment]
Hi @bharathkkb,

Environment variable can be of any type as in the below screenshot. Here `map(string)` or `list(objects)` cannot be the right types, as the values can be string, list or map. 

If we are restricting to only `string` then it is good to go and use `map(string)` instead of `list(objects)`. It wont break the existing application as the key name is considered as the indexed.

To include other types, I tried using `any` type of variable, but I am skeptical about the encoding being done for string env variable as well.

[Screenshot Env Variables](https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/assets/18209477/a48368c5-2a8f-4e49-a9c0-c94d4baedbf5)

**Comment by bharathkkb** [comment]
Thanks @prabhu34, where is the screenshot from? IIUC the provider restricts us to only string type?
https://github.com/hashicorp/terraform-provider-google/blob/c3f2efe0b182293c781e8630e46bc86fa6433112/google/services/cloudrun/resource_cloud_run_service.go#L1132
